# Generated by Django 5.2.8 on 2025-11-11 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('credential', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida')], max_length=5)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.accesspoint')),
            ],
        ),
    ]
