# Generated by Django 5.2.8 on 2025-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('id_users', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
