# Generated by Django 5.2.8 on 2025-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_visitor', models.CharField(max_length=10, unique=True)),
                ('visitor_type', models.CharField(choices=[('TEMP', 'Visitante Temporal'), ('PROV', 'Proveedor'), ('EMP', 'Empleado')], max_length=5)),
                ('motive', models.CharField(max_length=120)),
            ],
        ),
    ]
