# Generated by Django 5.2.8 on 2025-11-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_code', models.CharField(max_length=6)),
                ('active', models.BooleanField(default=True)),
                ('restricted', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField()),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
    ]
