# Generated by Django 5.2.8 on 2025-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='modelo',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='color',
            field=models.CharField(choices=[('1', 'ROJO'), ('2', 'AZUL'), ('3', 'VERDE')], max_length=1, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(max_length=10),
        ),
    ]
